version: '3.9'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab3
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'